name: habitos_app_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  shared_preferences: 2.2.2
  google_sign_in: ^6.2.1
  firebase_core: ^4.11.0
  firebase_messaging: ^16.4.1
  in_app_review: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true